# Generated by Django 4.2.1 on 2025-09-08 14:03

import detection.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("department", models.CharField(max_length=500)),
                ("radiologists", models.CharField(max_length=500)),
                ("contact_info", models.JSONField()),
                ("specialties", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.CharField(max_length=50, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("second_name", models.CharField(blank=True, max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("clinical_notes", models.TextField(blank=True)),
                ("hospital_id", models.CharField(max_length=50)),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("clinician_review", "Clinician Review"),
                            ("checkup_completed", "Checkup Completed"),
                            ("sent_to_radiologist", "Sent to Radiologist"),
                            ("xray_uploaded", "X-ray Uploaded"),
                            ("analysis_completed", "Analysis Completed"),
                            ("results_delivered", "Results Delivered"),
                        ],
                        default="registered",
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="XRaySubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_id",
                    models.CharField(
                        default=detection.models.generate_submission_id,
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_path",
                    models.FileField(upload_to=detection.models.get_upload_path),
                ),
                (
                    "body_part",
                    models.CharField(
                        choices=[
                            ("chest", "Chest"),
                            ("abdomen", "Abdomen"),
                            ("pelvis", "Pelvis"),
                            ("skull", "Skull"),
                            ("spine", "Spine"),
                            ("limbs", "Limbs"),
                            ("other", "Other"),
                        ],
                        default="chest",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("hospital_id", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("pending", "Pending"),
                            ("analyzing", "Analyzing"),
                            ("analyzed", "Analyzed"),
                            ("results_delivered", "Results Delivered"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="detection.patient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("clinician", "Clinician"),
                            ("radiologist", "Radiologist"),
                            ("receptionist", "Receptionist"),
                        ],
                        default="clinician",
                        max_length=20,
                    ),
                ),
                ("clinic_name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("clinician_assigned", "Clinician Assigned"),
                            ("checkup_completed", "Checkup Completed"),
                            ("sent_to_radiologist", "Sent to Radiologist"),
                            ("xray_uploaded", "X-ray Uploaded"),
                            ("analysis_completed", "Analysis Completed"),
                            ("results_delivered", "Results Delivered"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_clinician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_radiologist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="radiologist_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="detection.patient",
                    ),
                ),
                (
                    "receptionist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registered_patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis", models.CharField(max_length=255)),
                ("confidence", models.FloatField()),
                ("findings", models.TextField()),
                ("recommendations", models.TextField()),
                ("radiologist_notes", models.TextField(blank=True)),
                ("image_path", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "radiologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="detection.xraysubmission",
                    ),
                ),
            ],
        ),
    ]
